CREATE TABLE IF NOT EXISTS user (
    id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    first_name VARCHAR(24) NOT NULL,
    last_name VARCHAR(24) NOT NULL,
    email VARCHAR(24) NOT NULL,
    password VARCHAR(64) NOT NULL,
    lastLogin BIGINT DEFAULT UNIX_TIMESTAMP(NOW()),
    createdAt BIGINT DEFAULT UNIX_TIMESTAMP(NOW())
);
CREATE TABLE IF NOT EXISTS user_token (
    id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(64) NOT NULL,
    ip VARCHAR(15) NOT NULL,
    lastUsed BIGINT DEFAULT UNIX_TIMESTAMP(NOW()),
    createdAt BIGINT DEFAULT UNIX_TIMESTAMP(NOW())
);
CREATE TABLE IF NOT EXISTS `group` (
    id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `name` VARCHAR(24) NOT NULL,
    displayname VARCHAR(24) NOT NULL,
    createdAt BIGINT DEFAULT UNIX_TIMESTAMP(NOW())
);
CREATE TABLE IF NOT EXISTS user_perms (
    id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    permission VARCHAR(64) NOT NULL
);
CREATE TABLE IF NOT EXISTS group_perms (
    id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    group_id BIGINT NOT NULL,
    permission VARCHAR(64) NOT NULL
);
CREATE TABLE IF NOT EXISTS menu (
    id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    parent_id BIGINT DEFAULT NULL,
    `name` VARCHAR(32) NOT NULL,
    sort_id BIGINT NOT NULL,
    side_id BIGINT DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS side (
    id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `name` VARCHAR(32) NOT NULL,
    `path` VARCHAR(128) NOT NULL
);
CREATE TABLE IF NOT EXISTS side_content (
    id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    site_id BIGINT NOT NULL,
    content_id BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS content (
    id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    `type` VARCHAR(12) NOT NULL,
    content TEXT NOT NULL,
    createdAt BIGINT DEFAULT UNIX_TIMESTAMP(NOW())
);
CREATE TABLE IF NOT EXISTS content_history (
    id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    content_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    createdAt BIGINT DEFAULT UNIX_TIMESTAMP(NOW())
);